name: purana_bazzar
description: Purana Bazzar Flutter application



publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  carousel_slider: ^2.3.1
  cached_network_image: ^2.3.3
  shared_preferences: ^0.5.12+2
  simple_animations: ^2.2.3
  url_launcher: ^5.7.8
  fluttertoast: ^7.1.1
  like_button: ^1.0.4
  provider: ^4.3.2+2
  flutter_slidable: ^0.5.7
  google_maps_flutter: ^1.0.6
  image_picker: ^0.6.7+14
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_database: ^4.3.0
  google_sign_in: ^4.5.6
  geocoder: ^0.2.1
  geolocator: ^5.3.2+2
  permission_handler: ^5.0.1+1
  loading_overlay: ^0.2.1
  location: ^3.0.2
  neumorphic: ^0.4.0
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.0.1
  dio: ^3.0.10
  shimmer: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
